func s:fallback(value, fallback)
  if empty(a:value)
    return a:fallback
  else
    return a:value
  endif
endfunc

func s:xdg_config()
  return s:fallback($XDG_CONFIG_HOME, $HOME . "/.config")
endfunc

execute 'source' . fnameescape(s:xdg_config() . "/nvim/init.vim")
