/* eslint-disable no-magic-numbers,no-undef,semi */

user_pref('accessibility.force_disabled', 1);
user_pref('app.shield.optoutstudies.enabled', false);
user_pref('browser.discovery.enabled', false);
user_pref('browser.fixup.alternate.enabled', false);
user_pref('browser.formfill.enable', false);
user_pref('browser.newtabpage.enabled', false);
user_pref('browser.safebrowsing.downloads.remote.enabled', false);
user_pref('browser.urlbar.speculativeConnect.enabled', false);
user_pref('devtools.debugger.remote-enabled', false);
user_pref('devtools.inspector.activeSidebar', 'ruleview');
user_pref('devtools.inspector.showUserAgentStyles', true);
user_pref('devtools.inspector.three-pane-enabled', false);
user_pref('devtools.inspector.three-pane-first-run', false);
user_pref('dom.gamepad.enabled', false);
user_pref('dom.targetBlankNoOpener.enabled', true);
user_pref('extensions.fxmonitor.enabled', false);
user_pref('extensions.htmlaboutaddons.recommendations.enabled', false);
user_pref('extensions.pocket.enabled', false);
user_pref('font.default.x-western', 'sans-serif');
user_pref('font.name.monospace.x-western', 'PragmataPro Mono Liga');
user_pref('font.name.sans-serif.el', 'Source Sans Pro');
user_pref('font.name.sans-serif.ja', 'Source Han Sans');
user_pref('font.name.sans-serif.ko', 'Source Han Sans K');
user_pref('font.name.sans-serif.x-cyrillic', 'Source Sans Pro');
user_pref('font.name.sans-serif.x-unicode', 'Source Sans Pro');
user_pref('font.name.sans-serif.x-western', 'Source Sans Pro');
user_pref('font.name.sans-serif.zh-CN', 'Source Han Sans SC');
user_pref('font.name.sans-serif.zh-HK', 'Source Han Sans HC');
user_pref('font.name.sans-serif.zh-TW', 'Source Han Sans TC');
user_pref('font.name.sans.x-western', 'Source Sans Pro');
user_pref('font.name.serif.el', 'Source Serif Pro');
user_pref('font.name.serif.ja', 'Source Han Serif');
user_pref('font.name.serif.ko', 'Source Han Serif K');
user_pref('font.name.serif.x-cyrillic', 'Source Serif Pro');
user_pref('font.name.serif.x-unicode', 'Source Sans Pro');
user_pref('font.name.serif.x-western', 'Source Serif Pro');
user_pref('font.name.serif.zh-CN', 'Source Han Serif SC');
user_pref('font.name.serif.zh-HK', 'Source Han Serif TC');
user_pref('font.name.serif.zh-TW', 'Source Han Serif TC');
user_pref('gfx.color_management.enablev4', true);
user_pref('gfx.color_management.mode', 1);
user_pref('media.autoplay.default', 5);
user_pref('media.peerconnection.ice.default_address_only', true);
user_pref('media.peerconnection.ice.no_host', true);
user_pref('network.IDN_show_punycode', true);
user_pref('network.cookie.cookieBehavior', 3);
user_pref('network.cookie.thirdparty.sessionOnly', true);
user_pref('network.dns.disablePrefetch', true);
user_pref('network.http.referer.XOriginPolicy', 1);
user_pref('network.http.referer.XOriginTrimmingPolicy', 2);
user_pref('network.http.speculative-parallel-limit', 0);
user_pref('network.manage-offline-status', false);
user_pref('network.predictor.enabled', false);
user_pref('network.prefetch-next', false);
user_pref('network.proxy.socks_remote_dns', true);
user_pref('network.trr.mode', 5);
user_pref('permissions.default.desktop-notification', 2);
user_pref('permissions.default.geo', 2);
user_pref('plugin.state.flash', 0);
user_pref('privacy.clearOnShutdown.offlineApps', true);
user_pref('privacy.clearOnShutdown.siteSettings', true);
user_pref('privacy.firstparty.isolate', true);
user_pref('privacy.firstparty.isolate.restrict_opener_access', true);
user_pref('privacy.trackingprotection.cryptomining.enabled', true);
user_pref('privacy.trackingprotection.enabled', false); // Disable only if using uBlock Origin or similar
user_pref('privacy.trackingprotection.fingerprinting.enabled', true);
user_pref('privacy.trackingprotection.pbmode.enabled', false); // Disable only if using uBlock Origin or similar
user_pref('reader.content_width', 4);
user_pref('reader.font_size', 5);
user_pref('reader.font_type', 'sans-serif');
user_pref('reader.line_height', 3);
user_pref('security.mixed_content.block_display_content', true);
user_pref('security.mixed_content.block_object_subrequest', true);
user_pref('security.mixed_content.upgrade_display_content', true);
user_pref('signon.rememberSignons', false);
user_pref('toolkit.legacyUserProfileCustomizations.stylesheets', true);
user_pref('toolkit.telemetry.archive.enabled', false);
user_pref('toolkit.telemetry.enabled', false);
user_pref('toolkit.telemetry.unified', false);
